name: Mark stale issues

on: push

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue shows no activity for 21 days. It''s labeled stale until changed.'
        stale-issue-label: 'stale'
        days-before-stale: 1

